version: "3.8"
services:
  db:
    image: postgres:16
    container_name: finsmart-db
    environment:
      POSTGRES_DB: finsmartdb
      POSTGRES_USER: finsmart
      POSTGRES_PASSWORD: finsmartpwd
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finsmart -d finsmartdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dbdata:
